### ISSUE TITLE
Доработка поймай шарик

### ISSUE THREAD

**Issue by Ainoss** [Andrew-Kot/infa_2019_kotsevich#1]
Код похож на списанный, это не приветствуется. Пожалуйста, исправьте указанные в комментариях проблемы.
Дополнительное задание * - реализуйте пересоздание всех шариков каждые 10 секунд.

**Comment by Andrew-Kot** [comment]
Код не списывал, для понимания работы программы пользовался тем, что был предложен на семинаре (добавил столкновение со стенкой, сделал вывод результатов). Указанные проблемы в комментариях исправил

**Comment by Andrew-Kot** [comment]
Добавил версию 2.1, где реализовано заданное дополнительное задание

**Comment by Ainoss** [comment]
Здорово, принято! Добавил еще пару комментариев

**Comment by Andrew-Kot** [comment]
Всё сделано
