### ISSUE TITLE
Пушка

### ISSUE THREAD

**Issue by Ainoss** [Andrew-Kot/infa_2019_kotsevich#2]
Отличная работа! Все пункты задания выполнены, багов не замечено. Зачтено!

Однако я хотел бы напоследок указать на некоторые детали.
- Разделение на модули получилось не совсем органическим. Это должна быть вспомогательная универсальная сущность, например, универсальный класс ball. А у вас и классы там, и глобальные переменные, и логика;
- Вы оказались в шаге от масштабирования на произвольное число целей. Было бы еще лучше :) Еще хорошо было бы больше функционала засунуть в target.hit() (удаление канваса, обнуление жизней) и больше кода переиспользовать из родительского класса ball (например, move можно было сделать универсальнее за счет определенных констант и не переписывать для target)

Закрывайте issue когда ознакомитесь.

**Comment by Andrew-Kot** [comment]
Ознакомился
